name: Build Classic for Testing

on:
  pull_request:
    branches:
      - classic
  workflow_dispatch: null

env:
  ENABLE_ARTIFACTS_MODE: "true"
  MOZCONFIG: "./.mozconfig-ga"
  SHELL: "/bin/bash"

jobs:
  linux:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/hawkeye116477/waterfox_docker_img:latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Cache for Linux
        uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
          key: ${{ runner.os }}-${{ hashFiles('**/browser/config/version_display.txt') }}
      - name: Build
        run: |
          ./mach build
      - name: Package
        run: |
          ./mach package
        if: env.ENABLE_ARTIFACTS_MODE == 'true'
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact Classic Linux ${{ github.run_id }}
          path: ./objdir-*/dist/*.tar.bz2
        if: env.ENABLE_ARTIFACTS_MODE == 'true'
