name: Build Classic for Testing

on:
  pull_request:
    branches:
      - classic
  workflow_dispatch:

jobs:
    buildLinux:
        env:
            ENABLE_ARTIFACTS_MODE: "true"
            MOZCONFIG: "./.mozconfig-ga"
            SHELL: "/bin/bash"
        runs-on: ubuntu-18.04
        container:
          image: ghcr.io/hawkeye116477/waterfox_docker_img:latest
        steps:
          - name: Checkout branch
            uses: actions/checkout@v2
          - name: Cache for Linux
            uses: actions/cache@v2
            with:
              path: |
                ~/.ccache
              key: ${{ runner.os }}-${{ hashFiles('**/browser/config/version_display.txt') }}
          - name: Cleanup useless paths
            run: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf /opt/ghc
              sudo rm -rf /usr/local/share/boost
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          - name: Mach build
            run: |
              ./mach build
          - name: Mach package
            run: |
              ./mach package
            if: env.ENABLE_ARTIFACTS_MODE == 'true'
          - name: Upload Linux artifact
            uses: actions/upload-artifact@v2
            with:
              name: Artifact Classic Linux ${{ github.run_id }}
              path: ./objdir-*/dist/*.tar.bz2
            if: env.ENABLE_ARTIFACTS_MODE == 'true'
